# Generated by Django 4.0.2 on 2022-03-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_company_owner_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Отклики', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Специализации', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
