# Generated by Django 4.0.2 on 2022-03-15 19:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0005_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(blank=True, verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None,
                                                                 verbose_name='Ваш телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=64, verbose_name='Вас зовут'),
        ),
    ]
